Update opensrp web vars
opensrp/helm-charts pull request #15
Opened 2021-05-04 11:51 UTC by p-netm

Update opensrp web vars

2021-05-04 15:03 UTC, bennsimon approved these changes

2021-05-04 15:04 UTC, bennsimon requested changes

2021-05-04 15:04 UTC, bennsimon commented on charts/opensrp-web/values.yaml
> +  REACT_APP_ENABLE_LANGUAGE_SWITCHER: "{{.Values.frontEnd.enableLanguageSwitcher}}"
Space out the strings from the double braces.

2021-05-04 15:04 UTC, bennsimon commented on charts/opensrp-web/values.yaml
> +  REACT_APP_SENTRY_DSN: "{{.Values.frontEnd.sentryDsn}}"
```suggestion
  REACT_APP_SENTRY_DSN: "{{ .Values.frontEnd.sentryDsn }}"
```

2021-05-05 08:00 UTC, KipSigei commented
@p-netm could you update [this](https://github.com/opensrp/helm-charts/blob/8502e5c89fd1c575d7ee9cb113c3ba7880ca8466/charts/opensrp-web/values.yaml#L112) to `REACT_APP_ENABLE_TEAMS_ASSIGNMENT_MODULE`

2021-05-05 12:15 UTC, bennsimon approved these changes

2021-05-05 12:20 UTC, merged